/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GroupId = IDL.Nat64;
export const ClientInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'company' : IDL.Opt(IDL.Text),
  'groupId' : GroupId,
  'notes' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const ClientId = IDL.Nat64;
export const ClientGroupInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
});
export const ScriptInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'category' : IDL.Opt(IDL.Text),
});
export const ScriptId = IDL.Nat64;
export const ClientGroup = IDL.Record({
  'id' : GroupId,
  'name' : IDL.Text,
  'createdAt' : IDL.Nat64,
  'description' : IDL.Opt(IDL.Text),
});
export const Client = IDL.Record({
  'id' : ClientId,
  'name' : IDL.Text,
  'createdAt' : IDL.Nat64,
  'email' : IDL.Opt(IDL.Text),
  'company' : IDL.Opt(IDL.Text),
  'groupId' : GroupId,
  'notes' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const Script = IDL.Record({
  'id' : ScriptId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Nat64,
  'updatedAt' : IDL.Nat64,
  'category' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addClient' : IDL.Func([ClientInput], [ClientId], []),
  'addClientGroup' : IDL.Func([ClientGroupInput], [GroupId], []),
  'addScript' : IDL.Func([ScriptInput], [ScriptId], []),
  'deleteClient' : IDL.Func([ClientId], [], []),
  'deleteClientGroup' : IDL.Func([GroupId], [], []),
  'deleteScript' : IDL.Func([ScriptId], [], []),
  'getClientGroups' : IDL.Func([], [IDL.Vec(ClientGroup)], ['query']),
  'getClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getClientsByGroup' : IDL.Func([GroupId], [IDL.Vec(Client)], ['query']),
  'getScript' : IDL.Func([ScriptId], [Script], ['query']),
  'getScripts' : IDL.Func([], [IDL.Vec(Script)], ['query']),
  'getScriptsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Script)], ['query']),
  'getScriptsByTitle' : IDL.Func([], [IDL.Vec(Script)], ['query']),
  'updateClient' : IDL.Func([ClientId, ClientInput], [], []),
  'updateClientGroup' : IDL.Func([GroupId, ClientGroupInput], [], []),
  'updateScript' : IDL.Func([ScriptId, ScriptInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GroupId = IDL.Nat64;
  const ClientInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'company' : IDL.Opt(IDL.Text),
    'groupId' : GroupId,
    'notes' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const ClientId = IDL.Nat64;
  const ClientGroupInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
  });
  const ScriptInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'category' : IDL.Opt(IDL.Text),
  });
  const ScriptId = IDL.Nat64;
  const ClientGroup = IDL.Record({
    'id' : GroupId,
    'name' : IDL.Text,
    'createdAt' : IDL.Nat64,
    'description' : IDL.Opt(IDL.Text),
  });
  const Client = IDL.Record({
    'id' : ClientId,
    'name' : IDL.Text,
    'createdAt' : IDL.Nat64,
    'email' : IDL.Opt(IDL.Text),
    'company' : IDL.Opt(IDL.Text),
    'groupId' : GroupId,
    'notes' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const Script = IDL.Record({
    'id' : ScriptId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Nat64,
    'updatedAt' : IDL.Nat64,
    'category' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addClient' : IDL.Func([ClientInput], [ClientId], []),
    'addClientGroup' : IDL.Func([ClientGroupInput], [GroupId], []),
    'addScript' : IDL.Func([ScriptInput], [ScriptId], []),
    'deleteClient' : IDL.Func([ClientId], [], []),
    'deleteClientGroup' : IDL.Func([GroupId], [], []),
    'deleteScript' : IDL.Func([ScriptId], [], []),
    'getClientGroups' : IDL.Func([], [IDL.Vec(ClientGroup)], ['query']),
    'getClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getClientsByGroup' : IDL.Func([GroupId], [IDL.Vec(Client)], ['query']),
    'getScript' : IDL.Func([ScriptId], [Script], ['query']),
    'getScripts' : IDL.Func([], [IDL.Vec(Script)], ['query']),
    'getScriptsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Script)], ['query']),
    'getScriptsByTitle' : IDL.Func([], [IDL.Vec(Script)], ['query']),
    'updateClient' : IDL.Func([ClientId, ClientInput], [], []),
    'updateClientGroup' : IDL.Func([GroupId, ClientGroupInput], [], []),
    'updateScript' : IDL.Func([ScriptId, ScriptInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };