/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Client {
  'id' : ClientId,
  'name' : string,
  'createdAt' : bigint,
  'email' : [] | [string],
  'company' : [] | [string],
  'groupId' : GroupId,
  'notes' : [] | [string],
  'phone' : [] | [string],
}
export interface ClientGroup {
  'id' : GroupId,
  'name' : string,
  'createdAt' : bigint,
  'description' : [] | [string],
}
export interface ClientGroupInput {
  'name' : string,
  'description' : [] | [string],
}
export type ClientId = bigint;
export interface ClientInput {
  'name' : string,
  'email' : [] | [string],
  'company' : [] | [string],
  'groupId' : GroupId,
  'notes' : [] | [string],
  'phone' : [] | [string],
}
export type GroupId = bigint;
export interface Script {
  'id' : ScriptId,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'category' : [] | [string],
}
export type ScriptId = bigint;
export interface ScriptInput {
  'title' : string,
  'content' : string,
  'category' : [] | [string],
}
export interface _SERVICE {
  'addClient' : ActorMethod<[ClientInput], ClientId>,
  'addClientGroup' : ActorMethod<[ClientGroupInput], GroupId>,
  'addScript' : ActorMethod<[ScriptInput], ScriptId>,
  'deleteClient' : ActorMethod<[ClientId], undefined>,
  'deleteClientGroup' : ActorMethod<[GroupId], undefined>,
  'deleteScript' : ActorMethod<[ScriptId], undefined>,
  'getClientGroups' : ActorMethod<[], Array<ClientGroup>>,
  'getClients' : ActorMethod<[], Array<Client>>,
  'getClientsByGroup' : ActorMethod<[GroupId], Array<Client>>,
  'getScript' : ActorMethod<[ScriptId], Script>,
  'getScripts' : ActorMethod<[], Array<Script>>,
  'getScriptsByCategory' : ActorMethod<[string], Array<Script>>,
  'getScriptsByTitle' : ActorMethod<[], Array<Script>>,
  'updateClient' : ActorMethod<[ClientId, ClientInput], undefined>,
  'updateClientGroup' : ActorMethod<[GroupId, ClientGroupInput], undefined>,
  'updateScript' : ActorMethod<[ScriptId, ScriptInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];