/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ClientGroupInput {
    name: string;
    description?: string;
}
export interface ClientInput {
    name: string;
    email?: string;
    company?: string;
    groupId: GroupId;
    notes?: string;
    phone?: string;
}
export interface Script {
    id: ScriptId;
    title: string;
    content: string;
    createdAt: bigint;
    updatedAt: bigint;
    category?: string;
}
export interface ScriptInput {
    title: string;
    content: string;
    category?: string;
}
export interface ClientGroup {
    id: GroupId;
    name: string;
    createdAt: bigint;
    description?: string;
}
export type ScriptId = bigint;
export interface Client {
    id: ClientId;
    name: string;
    createdAt: bigint;
    email?: string;
    company?: string;
    groupId: GroupId;
    notes?: string;
    phone?: string;
}
export type ClientId = bigint;
export type GroupId = bigint;
export interface backendInterface {
    addClient(input: ClientInput): Promise<ClientId>;
    addClientGroup(input: ClientGroupInput): Promise<GroupId>;
    addScript(input: ScriptInput): Promise<ScriptId>;
    deleteClient(id: ClientId): Promise<void>;
    deleteClientGroup(id: GroupId): Promise<void>;
    deleteScript(id: ScriptId): Promise<void>;
    getClientGroups(): Promise<Array<ClientGroup>>;
    getClients(): Promise<Array<Client>>;
    getClientsByGroup(groupId: GroupId): Promise<Array<Client>>;
    getScript(id: ScriptId): Promise<Script>;
    getScripts(): Promise<Array<Script>>;
    getScriptsByCategory(category: string): Promise<Array<Script>>;
    getScriptsByTitle(): Promise<Array<Script>>;
    updateClient(id: ClientId, input: ClientInput): Promise<void>;
    updateClientGroup(id: GroupId, input: ClientGroupInput): Promise<void>;
    updateScript(id: ScriptId, input: ScriptInput): Promise<void>;
}
import type { Client as _Client, ClientGroup as _ClientGroup, ClientGroupInput as _ClientGroupInput, ClientId as _ClientId, ClientInput as _ClientInput, GroupId as _GroupId, Script as _Script, ScriptId as _ScriptId, ScriptInput as _ScriptInput } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addClient(arg0: ClientInput): Promise<ClientId> {
        if (this.processError) {
            try {
                const result = await this.actor.addClient(to_candid_ClientInput_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addClient(to_candid_ClientInput_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addClientGroup(arg0: ClientGroupInput): Promise<GroupId> {
        if (this.processError) {
            try {
                const result = await this.actor.addClientGroup(to_candid_ClientGroupInput_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addClientGroup(to_candid_ClientGroupInput_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addScript(arg0: ScriptInput): Promise<ScriptId> {
        if (this.processError) {
            try {
                const result = await this.actor.addScript(to_candid_ScriptInput_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addScript(to_candid_ScriptInput_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteClient(arg0: ClientId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClient(arg0);
            return result;
        }
    }
    async deleteClientGroup(arg0: GroupId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClientGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClientGroup(arg0);
            return result;
        }
    }
    async deleteScript(arg0: ScriptId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteScript(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteScript(arg0);
            return result;
        }
    }
    async getClientGroups(): Promise<Array<ClientGroup>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientGroups();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientGroups();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClients(): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClients();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClients();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClientsByGroup(arg0: GroupId): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientsByGroup(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientsByGroup(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScript(arg0: ScriptId): Promise<Script> {
        if (this.processError) {
            try {
                const result = await this.actor.getScript(arg0);
                return from_candid_Script_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScript(arg0);
            return from_candid_Script_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScripts(): Promise<Array<Script>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScripts();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScripts();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScriptsByCategory(arg0: string): Promise<Array<Script>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScriptsByCategory(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScriptsByCategory(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScriptsByTitle(): Promise<Array<Script>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScriptsByTitle();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScriptsByTitle();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateClient(arg0: ClientId, arg1: ClientInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClient(arg0, to_candid_ClientInput_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClient(arg0, to_candid_ClientInput_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateClientGroup(arg0: GroupId, arg1: ClientGroupInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClientGroup(arg0, to_candid_ClientGroupInput_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClientGroup(arg0, to_candid_ClientGroupInput_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateScript(arg0: ScriptId, arg1: ScriptInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateScript(arg0, to_candid_ScriptInput_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateScript(arg0, to_candid_ScriptInput_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ClientGroup_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClientGroup): ClientGroup {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Client_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Client): Client {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Script_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Script): Script {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ClientId;
    name: string;
    createdAt: bigint;
    email: [] | [string];
    company: [] | [string];
    groupId: _GroupId;
    notes: [] | [string];
    phone: [] | [string];
}): {
    id: ClientId;
    name: string;
    createdAt: bigint;
    email?: string;
    company?: string;
    groupId: GroupId;
    notes?: string;
    phone?: string;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        email: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.email)),
        company: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.company)),
        groupId: value.groupId,
        notes: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.notes)),
        phone: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ScriptId;
    title: string;
    content: string;
    createdAt: bigint;
    updatedAt: bigint;
    category: [] | [string];
}): {
    id: ScriptId;
    title: string;
    content: string;
    createdAt: bigint;
    updatedAt: bigint;
    category?: string;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        category: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.category))
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _GroupId;
    name: string;
    createdAt: bigint;
    description: [] | [string];
}): {
    id: GroupId;
    name: string;
    createdAt: bigint;
    description?: string;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        description: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.description))
    };
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Client>): Array<Client> {
    return value.map((x)=>from_candid_Client_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Script>): Array<Script> {
    return value.map((x)=>from_candid_Script_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClientGroup>): Array<ClientGroup> {
    return value.map((x)=>from_candid_ClientGroup_n8(_uploadFile, _downloadFile, x));
}
function to_candid_ClientGroupInput_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClientGroupInput): _ClientGroupInput {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ClientInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClientInput): _ClientInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ScriptInput_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ScriptInput): _ScriptInput {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
    company?: string;
    groupId: GroupId;
    notes?: string;
    phone?: string;
}): {
    name: string;
    email: [] | [string];
    company: [] | [string];
    groupId: _GroupId;
    notes: [] | [string];
    phone: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        company: value.company ? candid_some(value.company) : candid_none(),
        groupId: value.groupId,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description?: string;
}): {
    name: string;
    description: [] | [string];
} {
    return {
        name: value.name,
        description: value.description ? candid_some(value.description) : candid_none()
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    category?: string;
}): {
    title: string;
    content: string;
    category: [] | [string];
} {
    return {
        title: value.title,
        content: value.content,
        category: value.category ? candid_some(value.category) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
